src/BookingsModal.tsx
If accepted, this pull request will add links for walking and driving directions to the vaccine location.
This uses the [Apple Map Links URL scheme](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html)
- On Android, the link will open the Google Maps App (if installed), or Apple Maps web version
- On iOS, the link will open Apple Maps App
- On Windows, the link will open the Windows Maps App (if installed), or Apple Maps web version
=> Add walking directions and better maps support

src/booking/BookingsModal.tsx
As per https://www.w3.org/TR/html401/struct/text.html#h-9.3.1 we cannot have a h3 tag nested within a p tag as p tags only allows inline elements.
This PR switches the p tag to a div to remove the react warning messages.
Addresses #61
=> fix: remove warning for h3 an p tag nesting

src/LanguageSelect.tsx, src/translations/resources.ts
Language selector doesn't change its value/label when the user changes the language. I may swap the code around for the id in another PR as it's rather redundant.
https://github.com/CovidEngine/vaxxnz/issues/64
=> Fixed language selector

src/LanguageSelect.tsx, src/booking/BookingCalendar.tsx, src/booking/BookingsModal.tsx, src/translations/index.ts, src/translations/resources.ts, src/utils/locale.ts
This PR fixes some issues in date localisation so that the month on the top of the calendar ("September 2021"), the date in the calendar ("21 Sep") and in the calendar modal can be localised following different regions convention.
=> Fix localised calendar string in BookingCalendar and BookingsModal

.husky/pre-commit
We should use the locally pulled `lint-staged` binary to ensure all developers use the same version. We also can't be sure that a developer has `lint-staged` installed globally especially since our current requirements are Node and Yarn, so that would prevent them from committing their changes as the pre-commit hook would fail.
Related to #77
=> Use local lint-staged binary

src/LanguageSelect.tsx
Sets `placeholder` of `Select` to `"English"` in `LanguageSelect.tsx` so language select drop down will display English by default per issue #123.
Let me know if it needs any tweaking!
=> sets language selecter placeholder to English

src/LanguageSelect.tsx, src/translations/index.ts, src/translations/resources.ts
Added the `?locale=[code]` into the query string to make it shareable while maintaining the originally selected language (closes #98).
I have also reordered the language detector to prioritise language selection in this order: `["querystring", "localStorage", "navigator"]` and tidied up the code.
=> Shareable links for languages

package.json, src/translations/scripts/syncTranslations.ts, yarn.lock
This PR removes the `lodash` dev dependency. Previously required `lodash` functions have been re-written in JS in the hope that this reduces the bundle size as per #151
=> Removed lodash

src/utils/locale.ts
Only import locale object that we support to avoid gigantic bundle size from `date-fns`. Some how this fix issue with time string display for different locale too 🤷 
Before 
After:
=> [Bundle size] Fix issue with bundle size too big

src/translations/scripts/syncTranslations.ts
This PR adds the ability to auto format the translation files with `prettier` when they sync.
Prior to this, a new line was not added to the end of the JSON files, causing CI to fail. Writing the data using `prettier` formatting ensures the new line is automatically added.
=> Format translations with Prettier on i18n sync (trailing new line)

src/utils/locale.ts
I also tried to trim down bundle size further but unsure  how to trim that fat `Select` component from base.UI
=> [Date locale] Fix wrong key value mapping between i18 and date-fns locale

src/calendar/Calendar.tsx
Addresses the bug of dates not translating when changing language.
=> Re-render CalendarMonthContainer when language changes

src/calendar/CalendarData.ts, src/calendar/booking/BookingData.ts, src/calendar/booking/BookingDataTypes.ts
We had an issue: when memoizing `byMonth: BookingData`, crowdsourced location would start duplicating in the date modal. I had to disable memoizing due to this issue. That affects performance.
This was happening because Oli did `day.push(location);` in a mutating fashion to a memoized array - it would fill up over multiple renders. 
The solution is to put `day.push(location);` code BEFORE memoize happens. That is, into `getBookingData`.
This PR puts `day.push(location);` code into `getBookingData` and enables back memoizing.
@oeed please review this code. Can you poke holes in it? Btw, your code worked perfectly before I introduced `useMemo`, so it was my bad for not testing it properly.
Cheers.
=> Put crowdsource location merge closer to `BookingData` generation

.github/workflows/ci.yaml, .gitignore
This PR adds package-lock.json to our .gitignore file. An additional check is also added into our presubmit jobs to be safe.
=> Prevent package-lock.json being committed

src/crowdsourced/CrowdsourcedLocations.ts
1.  remove life pharmacy rangiora as it is now on bookmyvaccine
=> remove life pharmacy rangiora

src/calendar/modal/CalendarModal.tsx
1. Avoid using animation. Because there's a css animation delaying closing modal for a few seconds. Another fix I can think of is using `setTimeout` but it seems ugly. This solution will make UX a little bit less nice I guess 🤷 
Address https://github.com/CovidEngine/vaxxnz/issues/145
This is the animation applied to the modal
After the fix, the modals seems snappier so there's a cons about not using animation.
https://user-images.githubusercontent.com/29682322/133588424-74247213-e607-4111-81df-90640c55cff6.mov
=> Fix issue with modal display empty modal for a split second

src/calendar/BookingLocation.tsx, src/utils/date.ts
1. Added a function to parse and format slot time based on language
Closes #187
=> Fix: format slot times according to locale

src/calendar/BookingLocation.tsx
1. return null from BookingLocation.tsx if the slots length is 0 (this can happen after MOH endpoint update)
Slight flicker on scroll. I believe this is because the moh api call is made on scroll
=> Fix issue #221 - Locations with no slots are still displayed after MOH endpoint update.

CONTRIBUTING.md
1. This is simply to fix the link to CONTRIBUTING_DEV which wasn't updated after renaming the file.
=> Fix a broken link for CONTRIBUTING_DEV

src/calendar/BookingLocation.tsx, src/translations/locales/common_ar-IQ.json, src/translations/locales/common_de-DE.json, src/translations/locales/common_en-NZ.json, src/translations/locales/common_es-ES.json, src/translations/locales/common_hi-HI.json, src/translations/locales/common_id-ID.json, src/translations/locales/common_ja-JP.json, src/translations/locales/common_mi-NZ.json, src/translations/locales/common_ms-MY.json, src/translations/locales/common_pl-PL.json, src/translations/locales/common_ru-RU.json, src/translations/locales/common_sm-SM.json, src/translations/locales/common_tl-PH.json, src/translations/locales/common_to-TO.json, src/translations/locales/common_vi-VN.json, src/translations/locales/common_zh-CN.json, src/translations/locales/common_zh-TW.json
Kia ora,
_Just to give a rough idea how well I know Polish and English:_
I was born in Poland and Polish is my native language. My CEFR English level is
C1 and I have translated a huge % of Tor's website (over 900 strings, can't
tell the exact numbers).
---
- Some strings were outdated(?)
- Some of the strings sounded like something taken from Google Translate (very literal translation)
> `"roadmap": "Mapa drogowa"` - makes no sense if you don't know the English word
> `"rawData": "Dane podstawowe"` - weird (in literal translation - basic data)
> `"cancel": "Odwołać"` - weird choice if we consider context
- Some were not translated
> `"10closest": "10 closest"`
> `"mistake": "Did we make a mistake?"`
> `"changeOrCancelABooking": "Change or cancel a Booking"`
I also wanted to translate …
=> Improve Polish translation

src/VaxComponents.js
Same fix for walk-in opening time alignment as availability label
Tested on macOS big sur:
Safari 14.1.2
Google Chrome 94
Microsoft Edge 93
=> Fix walk-in opening time alignment for Safari

README.md, src/Footer.tsx
1. Backlink to vaxx.nz widget
Link juice
=> Backlink to vaxx.nz widget

src/VaxComponents.js
1. Force zIndex for the month section to fix overlay issues on scroll
if unclear of what's breaking, while scrolling the month section falls behind the days & text.
before: https://i.imgur.com/5Nrgx5e.png
after: https://i.imgur.com/oJpRI1s.png
=> Force z-index on MonthSection

src/crowdsourced/CrowdsourcedLocations.ts
1. Delete last crowdsourced location
Part of our strategy of outsourcing all the site profiling to Healthpoint
=> Delete last crowdsourced location

src/calendar/CalendarError.tsx
1. Changed Report Error button text in CalendarError.tsx to uppercase
Fixes  #322 
Before
After
=> fix: capitalised Report Error button to keep styling consistent

src/calendar/Calendar.tsx, src/translations/locales/common_en-NZ.json
1. If there are no bookings available, it displays an error message instead of a calendar full of "0 bookings available".
2. Added "noVacApptToBook" to en-NZ translation.
Closes #274
=> Show CalendarError when there are no locations around you

CONTRIBUTING.md, CONTRIBUTING_DEV.md, README.md, src/Footer.tsx, src/Header.tsx, src/calendar/CalendarError.tsx, src/calendar/booking/BookingData.ts, src/faq.tsx, src/today-locations/healthpoint/HealthpointData.ts, src/translations/scripts/uniqCrowdsourced.ts
1.  Replaced links that reference CovidEngine to reference vaxxnz instead
fixes #326
=> fix: replaced links to reference vaxxnz instead of CovidEngine
