vaxxnz/vaxxnz

- src/BookingsModal.tsx
Revert "Revert "Add directions" - let's ship it separately" sorry didn't realise its already shipped
> Reship directions

- README.md
> Fix bookmyvaccine link in README

- src/App.css
- src/VaxComponents.js
remove :hover state and increase icon size on mobile
> little usability tweaks

- src/LanguageSelect.tsx
- src/location-picker/LocationPicker.tsx
- src/translations/es/common.json
- src/translations/index.ts
- src/translations/resources.ts
Updated Language Select component to show options based on translations configuration
Updated Location Picker component to show the language select.
> Updated Language Select component and added it to Location picker

- src/LanguageSelect.tsx
- src/translations/index.ts
This PR saves a user's language choice into local storage so it is
persisted on page reloads.
Addresses #68
> Persist user's language choices

- README.md
Added updated screenshot of the homepage
> New Banner Image

- src/translations/locales/common_sm-SM.json
Text left untranslated is intentional.
> Refactor Samoan translation

- src/VaxxTheme.js
Addresses issue #116 by adding more fonts to `VaxxTheme.js` so that Русский is displayed in a nicer looking font than `sans-serif`, since Roboto does not handle Cyrillic characters.
If there's a better font to use for handling Cyrillic, let me know and I can add it and resubmit!
> fixes LanguageSelect.tsx font to better handle Cyrillic

- src/translations/locales/common_de-DE.json
- src/translations/locales/common_sm-SM.json
> refactor: add missing Samoan translations

- src/translations/README.md
- src/translations/index.ts
- src/translations/locales/common_vi-VN.json
- src/translations/resources.ts
adds translations for Vietnamese - courtesy of @nicktran29
> Vietnamese translations

- src/translations/locales/common_vi-VN.json
Translate `Thanks to Address Lookup service ` message
> [Translation] Add new translation for Vietnamese

- src/LanguageSelect.tsx
fixes contrast ratio issue on language picker and fixes text-wrapping issue as well
> fix a11y issue on language selector

- src/translations/locales/common_ms-MY.json
- src/translations/resources.ts
added recommendations from a Bahasa Melayu native speaker
> Improve Bahasa Melayu translations

- src/translations/locales/common_zh-TW.json
> Fixes for traditional Chinese translation

- src/translations/locales/common_zh-CN.json
> Chinese Simplified translations updates

- src/today-locations/healthpoint/HealthpointModal.tsx
Fix issue: Missing 'Address' translation #158
> Fix address

- src/translations/locales/common_pl-PL.json
update request for polish instructions
> update polish language

- src/translations/index.ts
- src/translations/locales/common_id-ID.json
- src/translations/locales/common_in-ID.json
- src/translations/resources.ts
- src/utils/locale.ts
> Add Indonesian translation for vaxx

- src/translations/resources.ts
> Fix Indonesian

- package.json
- src/translations/locales/common_id-ID.json
Add `.json`for prettier to pick up.
Separate settings for linting and formatting.
Running prettier prior to formatting.
> Tidy up "lint-staged" config

- src/App.tsx
small tweak to footer to test netlify webhooks
> small tweak to footer to test netlify webhooks

- src/index.css
test webhooks with footer line height change
> test webhooks with footer line height

- src/crowdsourced/CrowdsourcedLocations.ts
updates auckland airport drive-thru vaccination address to correct one
> Update auckland airport address

- src/calendar/BookingLocation.tsx
If approved, this PR will:
Hide slots in the past in booking modal
> Hide old slots on Booking modal

- src/utils/array.spec.ts
- src/utils/array.ts
- src/utils/distance.spec.ts
- src/utils/distance.ts
- src/utils/math.spec.ts
- src/utils/math.ts
This PR adds more tests to existing functions within `src/utils`, as well as improving code documentation and adding return types.
> Add tests to existing utils functions

- src/translations/locales/common_mi-NZ.json
There is a review of some phrases in the VaxxNZ discord by **Nani** which I didn't implement.
I've left this as I feel it requires another review with the parties who have already made the translation.
> Correct the use of "i" in Te Reo Māori

- CONTRIBUTORS.md
> Discord link expired

- src/calendar/booking/BookingData.ts
- src/today-locations/healthpoint/HealthpointData.ts
1. Switch `37f2add75e38be7a929534b4329f42c44a1d5b6d` back to `main` since the crisis been dealt with
We've been running on rolled-back Netlify deploy since the morning.
> Switch pinned commit to main to reflect prod

- src/translations/locales/common_mi-NZ.json
1. Replace capitalised "I" with "i"
> Fix mi translation

- src/HomePage.tsx
1. Improve prominence on tab UI
> improve tab UI

- src/calendar/BookingLocation.tsx
> Capitalization hotfix

- CONTRIBUTING.md
1. this was reverted, putting it back
#244 introduced regression
> Fix a broken link for CONTRIBUTING_DEV

- src/today-locations/healthpoint/HealthpointModal.tsx
- src/translations/locales/common_ar-IQ.json
- src/translations/locales/common_de-DE.json
- src/translations/locales/common_en-NZ.json
- src/translations/locales/common_es-ES.json
- src/translations/locales/common_hi-HI.json
- src/translations/locales/common_id-ID.json
- src/translations/locales/common_ja-JP.json
- src/translations/locales/common_mi-NZ.json
- src/translations/locales/common_ms-MY.json
- src/translations/locales/common_pl-PL.json
- src/translations/locales/common_ru-RU.json
- src/translations/locales/common_sm-SM.json
- src/translations/locales/common_tl-PH.json
- src/translations/locales/common_to-TO.json
- src/translations/locales/common_vi-VN.json
- src/translations/locales/common_zh-CN.json
- src/translations/locales/common_zh-TW.json
- src/translations/scripts/syncTranslations.ts
This is an extension of #235 - somethings went wrong there, code has been merged but translations have not synced yet - meaning they automatically fall back to en-NZ in prod. This PR aims to add these missing (healthpoint) translations based on the work @gpoliko has done in #235.
> Added missing translation keys

- src/index.css
1.  add back in div:last-child css z-index 
Fixes the weird z-index issue
before: https://i.imgur.com/RTAd3ED.png
after: https://i.imgur.com/Erq9oBF.png
> fix set location card

- src/scroll.ts
1. useEffect => useLayoutEffect so that is runs just before painting
Someone tell me if this is a bad idea, all i know is it seems fixed
https://github.com/CovidEngine/vaxxnz/issues/234
> Fix page flicker on load

- src/HomePage.tsx
1.  improve tab color contrast to pass aria checks
2. disgusting fix for aria tab roles
> ugly, disgusting fix for tabs

- src/HomePage.tsx
- src/calendar/Calendar.tsx
- src/calendar/CalendarError.tsx
- src/today-locations/TodayLocationsSection.tsx
- src/translations/locales/common_en-NZ.json
- src/translations/locales/common_zh-CN.json
> Chinese simplified translations

- src/HomePage.tsx
- src/calendar/Calendar.tsx
- src/calendar/CalendarError.tsx
- src/today-locations/TodayLocationsSection.tsx
- src/translations/locales/common_en-NZ.json
- src/translations/locales/common_zh-CN.json
> Fixed missing Internationalization and updated Chinese Simplified

- src/scroll.ts
- src/utils/parsePhone.ts
This just fixes the warnings from this one file and removes some console.logs
> Fix warnings and remove console.logs

- src/translations/locales/common_zh-TW.json
> Updated Chinese Traditional translations

- src/VaxComponents.js
> Fix availability alignment for Safari

- src/translations/locales/common_en-NZ.json
1. add missing translation key
Was a bad merge
> Hotfix: add missing translation key

- src/calendar/Calendar.tsx
- src/today-locations/TodayLocationsSection.tsx
- src/utils/customSpinner.ts
created a customSpinner.ts in utils to style spinner more easily
1. Changed <Spinner to <StyledSpinnerNext
2. Add a customSpinner.ts so spinner can be style more easily
> Changed <Spinner to <StyledSpinnerNext

- src/scroll.ts
Scroll resets when navigating from a non-home path to a different non-home path
> Reset scroll when picking different location

- src/App.tsx
- src/cookiesPolicy.tsx
- src/privacyPolicy.tsx
- src/termsAndConditions.tsx
1. Removed react markdown from App component
2. Replaced Legal Pages markdown with equivalent React Component
3. Added margins for better styling
> Improve legal pages styling and remove markdown

- src/LanguageSelect.tsx
1. Adds font awesome globe icon to language dropdown to help people realise they can change language
> Add globe icon to language dropdown

- src/translations/locales/common_sm-SM.json
1. Add missing sm-SM translations
> refactor: add missing sm-SM translations

- src/translations/locales/common_tl-PH.json
1. Update Filipino translations.
> Update Filipino translations

- src/index.css
> Fixed #285 :Image elements do not have explicit width and height

- public/index.html
- src/location-picker/LocationModal.tsx
- src/location-picker/addressFinder.d.ts
- src/utils/useAddressFinder.ts
- src/utils/useAddressFinderLazy.ts
1. Load AddressFinder script tag in an async fashion
2. Load Google Fonts in an async fashion
Improves TTI
> Feature/load addressfinder+fonts lazily

- src/index.css
- src/location-picker/LocationModal.tsx
- src/location-picker/LocationPicker.tsx
1. Force z-index 1 while a user is setting their location, fixes overlay issues.
> Month section & Header hotfix

- package.json
- src/calendar/modal/CalendarModal.tsx
- src/crowdsourced/CrowdsourcedModal.tsx
- src/today-locations/TodayLocationsSection.tsx
- src/today-locations/healthpoint/HealthpointModal.tsx
- yarn.lock
1. Remove react-responsive replacing with styletron-react components
2. Replace the styled-components component in TodayLocationSection.tsx with a styletron-react component.
Closes #303
> Remove react responsive

- src/today-locations/healthpoint/HealthpointModal.tsx
fixes #328 
1. removed margin styling on back button
> Fix: removed margin on back button 

- src/today-locations/TodayLocationsSection.tsx
fixes #332 
1. modalPath function was being provided the incorrect index number
The index number provided to modalPath() did not match the index of that record in the original locations object. The locations.ok array is now being parsed with findIndex to get the correct index to pass into modalPath
> fixed bug where an incorrect link was provided for walk in locations

- src/App.css
- src/App.tsx
- src/HomePage.tsx
- src/translations/locales/common_en-NZ.json
- yarn.lock
1. Hides calendar as it is currently not working - scraper infrastructure requires work
> Temporary fix to hide calendar
